

proc Staircase(float $stair, float $length, float $width, float $height, float $pivitPoint, float $stepHeight, float $rotation)
{
        
        polyCube -width $width -height $height -d $length;
        xform -rotatePivot 0 0 $pivitPoint;
    for ($i=0; $i<=$stair; $i++)
    {
        duplicate -rr;
        move -r 0 $stepHeight 0;
        rotate -r 0 $rotation 0;
    }
}

Staircase(100,3,1,.2,3,.2,4);



